### ISSUE TITLE
fizmo-ncursesw with invalid game data crashes with signal 11, terminal left in dirty state

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#10]
Feeding Glulx game file (unsupported data) to fizmo-ncursesw crashes app. For example, `fizmo-ncursesw CounterfeitMonkey.gblorb` results in signal 11 with the terminal left in a messed-up state and the user has to run 'reset' to heal terminal.  Datafile can be downloaded here: http://ifdb.tads.org/viewgame?id=aearuuxv83plclpl

**Comment by chrender** [comment]
This has been fixed in fizmo commit 2510e74efd1ee80e8bccadab3a1fbfa55cf2d4bb.

**Comment by BroadcastGames** [comment]
I might have been in a somewhat long subdir at first.

cd /interactive_fiction_nineteen_eighty_nine/development_duplicate_here/a/b/c/d/e/f/g
fizmo-nursesw ReallyLongFilenameForData
