### ISSUE TITLE
./configure remglk passes tests but fails to compile, include "glk.h", on Ubuntu 16.10

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#12]
FYI, I noticed ./configure remglk missing a file. Here is the steps I'm using:

	mkdir fizmo_emptydir
	cd fizmo_emptydir
	git clone https://github.com/erkyrath/remglk.git
	cd remglk
	make
	cd ..

	git clone --recursive https://github.com/chrender/fizmo
	cd fizmo
	autoreconf -fi
	mkdir -p $HOME/opt/fizmo
	./configure --prefix=$HOME/opt/fizmo --enable-remglk --with-remglk-includedir=../remglk --with-remglk-libdir=../remglk
	make -j4 install

./configure passes it's tests, here is the relevant output:

	checking glk.h usability... no
	checking glk.h presence... no
	checking for glk.h... no
	checking for ../remglk/glk.h... yes
	checking remglk.h usability... no
	checking remglk.h presence... no
	checking for remglk.h... no
	checking for ../remglk/remglk.h... yes
	checking for main in -lremglk... no
	checking for libremglk in ../remglk... yes

However, the compile itself fails with this relative path. `glk_interface.c:39:17: fatal error: glk.h: No such file or directory
 #include "glk.h"` (in the middle of the output messages, pretty easy to miss).

The workaround is to not use a relative path "../" for the remglk parameters and to use a full path. Such as:

	./configure --prefix=$HOME/opt/fizmo --enable-remglk --with-remglk-includedir=/home/scratch/fizmo_emptydir/remglk --with-remglk-libdir=/home/scratch/fizmo_emptydir/remglk

Thank you.

**Comment by chrender** [comment]
This has been fixed in fizmo's commit 93da66e9be291e45f095307d0a9a2bc14229a82d and will be released in fizmo version 0.8.6.
