### ISSUE TITLE
fizmo-ncursesw & fizmo-sdl2 both segmentation fault on robots.z5

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#15]
As soon as you move the cursor in the game, hard crash. http://ifdb.tads.org/viewgame?id=hvnocxjj0z1q2pi0 - also note that the Inform source code is published. Thank you.

EDIT: zsnake.z5 also causes hard crashes / segmentation fault / on both variations: http://ifdb.tads.org/viewgame?id=dlo4yld75dljqia7

**Comment by chrender** [comment]
This is now fixed in 8fe5d147ec0244028fa6bfde68161044bbe98c28 and will be released in version 0.8.5.
