### ISSUE TITLE
fizmo-ncursesw with custard.z7 "More than 15 locals are not allowed."

### ISSUE THREAD

**Issue by RoundSparrow** [chrender/fizmo#18]
fizmo-sdl2 exits at the same point. Game data file here: http://ifdb.tads.org/viewgame?id=6bc1tdt0r14k8xa4 Ubuntu 16.10 x64. Mainstream games work fine on the same build.

**Comment by chrender** [comment]
This is fixed in the current github repositories and will be available in fizmo 0.8.4 and libfizmo 0.7.14.
