### ISSUE TITLE
Unable to fully initialize submodules

### ISSUE THREAD

**Issue by DavidGriffith** [chrender/fizmo#19]
After cloning the repo and doing ```git submodule init ; git submodule update```, this is printed:
```
$ git submodule update
fatal: reference is not a tree: 3aff105c8b301f48d5f40c994652da3ab9ff38a4
Unable to checkout '3aff105c8b301f48d5f40c994652da3ab9ff38a4' in submodule path 'libfizmo'
```
The ```libfizmo/``` directory is left empty.

**Comment by chrender** [comment]
Thanks for reporting this. The problem should by now be fixed, maybe you can give it a try.

**Comment by DavidGriffith** [comment]
Looks good.  Thanks!
