### ISSUE TITLE
fizmo-ncursesw crashes on startup

### ISSUE THREAD

**Issue by DavidGriffith** [chrender/fizmo#20]
Using master, I built fizmo and tried to execute ```fizmo-ncursesw/src/fizmo-ncursesw/fizmo-ncursesw```.  This resulted in this output:

```
$ ./fizmo-ncursesw 
Unknown i18n error.$
```

Note that there's no trailing newline with that error message.

**Comment by chrender** [comment]
The fizmo-frontends – like fizmo-ncursesw – are using various files provided by the underlying libraries, such as libfizmo, which include the internationalization (“i18n”) files. Without installing the entire fizmo distribution – or at least the required libraries – first, fizmo-ncursesw wont be able to find these files and won't be able to run.

**Comment by chrender** [comment]
Seeing that this issue still open I should probably add that you'll also have to install fizmo-ncursesw itself – using `make install` – since it's looking for the i18n files at the installation location, not in the sources.
