### ISSUE TITLE
Unsigned comparisons

### ISSUE THREAD

**Issue by angstsmurf** [chrender/fizmo#24]
As discussed in [this thread](https://intfiction.org/t/tethered-claims-fizmo-is-broken/41148), the Dialog runtime detects Fizmo as doing unsigned comparisons and refuses to run.

I guess those fixme comments in the source for [opcode_inc_chk](https://github.com/chrender/libfizmo/blob/e121fe48d17635b02f4a2c90e33f5eed1b88f4cb/src/interpreter/mathemat.c#L150) and [opcode_dec_chk](https://github.com/chrender/libfizmo/blob/e121fe48d17635b02f4a2c90e33f5eed1b88f4cb/src/interpreter/mathemat.c#L197) are about this.

**Comment by lft-linus** [comment]
The underlying problem is this one: #25 The comparison ops are working fine. Sorry for the confusion.

**Comment by angstsmurf** [comment]
Yeah, I made a pull request of the fix here: https://github.com/chrender/libfizmo/pull/2

Closing this.
