### ISSUE TITLE
Fizmo won't restore save games made by Dialog

### ISSUE THREAD

**Issue by angstsmurf** [chrender/fizmo#26]
See https://intfiction.org/t/fizmo-cannot-restore-tethered/41272

When I try to restore a save made with Fizmo, Tethered gives the error:

```
Game state restored successfully.

(Technical trouble: Invalid error code! Attempting to recover with UNDO.)

Undoing the last turn.

(Technical trouble: Invalid error code! Attempting to recover with UNDO.)

Undoing the last turn.

(Technical trouble: Invalid error code!)
```

This seems to be a problem common to all Zcode games written in Dialog. In the thread linked above, Linus Åkesson writes:

> Frotz, Gargoyle, and Fizmo all produce slightly different quetzal save files. Frotz and Gargoyle can restore savefiles produced by either interpreter, but Fizmo cannot restore from Frotz, Gargoyle, or itself. My minimal test program (see below) doesn’t crash immediately like Tethered, but if you press return after restoring, the program jumps into the error handler, which is wrong.
> 
> There’s something strange going on in Fizmo’s save files. Looking at the Stks chunk of a Tethered savefile, I see a frame with 56 words on the eval stack (all zero), whereas I know that my routines push at most one word, and then immediately pop it. And when saving from the small test program, I get the following as part of Stks:
> 
> 0012d6 00 01 01 0000
> 
> That’s a routine with zero local variables, but argument ‘a’ was passed. This appears to be a violation of the spec. Also, the call instruction just before 0012d6 does not pass an argument.
> 
> But for the particular crash we’re looking at, my best guess is that something is still wrong with catch/throw. Both runtime errors and regular failures can be invoked using throw, and their handlers are (naturally) installed at different stack levels. So if Fizmo somehow rewinds the stack one time too much, this would happen. But it’s confusing, because I thought we just fixed that error, and I don’t see why it would work differently across a save/restore. So perhaps the answer is in the weird Stks frames after all.

**Comment by chrender** [comment]
Thanks for reporting this! As it turned out, the number of stack frames was incorrectly counted when restoring a game, so the `throw` opcode would rewind to the wrong frame. I've tested the current version with `tethered-rel2.zblorb` and the dialog save test from the thread referenced above and as far as I can see the problem appears to be solved.
