### ISSUE TITLE
fizmo-sdl2 vs. fizmo-ncursesw, sdl2 output with story Alpha.z5

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#7]
Hello. Testing with Alpha.z5 from here: http://ifdb.tads.org/viewgame?id=nidzkipeux0uusqk Also noteworthy that the tads.org website contains the Inform source code for reference. Two identifiable issues:

1. The opening screen does not show a quote from "-- Queen, '39" on SDL2. It renders a black screen.
2. After the opening quote screen, the "Control room" prompt of ">" disappears. The cursor is positioned at the 2nd character from the left of the screen, but the prompt is only shown for like 1 second and then disappears.

Related to the number 2 on the list, the story does uses a timer that updates the status-window with a "Counter:" that changes every second.  It almost looks like the cursor prompt of ">" disappears after the first redraw of the status line?

**Comment by chrender** [comment]
The broken display of the opening screen should be fixed in fizmo commit faa5f11dd889b8b9f732d5f0344189fc3341b5fa.

**Comment by chrender** [comment]
As of commit version 9af2d35e5ae43adba089bcb2e34f3400f18d7e5f, both of these issues are fixed in fizmo. Thanks for the bug report.
