### ISSUE TITLE
fizmo-sdl2 vs. fizmo-ncursesw, sdl2 inverse text differences with story AtWork.z5

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#8]
Hello! Story file here: http://ifdb.tads.org/viewgame?id=p0sm7uf4nvwovubo

The opening screen 'press any key to continue' and the second-screen prompt render in inverse text, white on black. fizmo-sdl2 doesn't seem to 'close' the inverse text on the opening screen and renders a large block of white.

Issues #6 and Issue #7 may be related to some of these rendering issues. So I'll refrain from reporting similar issues on other stories except as comments if I suspect they are associated examples.  Thank you!

**Comment by chrender** [comment]
The opening screen issue has been fixed for “AtWork.z5”. This also fixes some other similar issues, for example in Photopia.
